-- TODO: add some parsing logic so that the source data text file is parsed into two tables
-- directly, rather than me manually splitting the data up into two files.

DROP TABLE IF EXISTS day05_position;
CREATE TABLE day05_position (
   c1 TEXT[]
 , c2 TEXT[]
 , c3 TEXT[]
 , c4 TEXT[]
 , c5 TEXT[]
 , c6 TEXT[]
 , c7 TEXT[]
 , c8 TEXT[]
 , c9 TEXT[]
);
COPY day05_position FROM '/aoc2022_data/day05_position.txt' WITH (DELIMITER ';');

DROP TABLE IF EXISTS day05_moves;
CREATE TABLE day05_moves (
   id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
 , description TEXT
);
COPY day05_moves (description) FROM '/aoc2022_data/day05_moves.txt';
