DROP TABLE IF EXISTS day05_data;

CREATE TABLE day05_data (
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , data text
);

COPY day05_data (data) FROM '/aoc2022_data/day05.txt';

DROP TABLE IF EXISTS day05_position;

CREATE TABLE day05_position AS
WITH cols AS (
  SELECT
      id
    , SUBSTRING(data, 2, 1) c1
    , SUBSTRING(data, 6, 1) c2
    , SUBSTRING(data, 10, 1) c3
    , SUBSTRING(data, 14, 1) c4
    , SUBSTRING(data, 18, 1) c5
    , SUBSTRING(data, 22, 1) c6
    , SUBSTRING(data, 26, 1) c7
    , SUBSTRING(data, 30, 1) c8
    , SUBSTRING(data, 34, 1) c9
  FROM day05_data
  WHERE id < 9
)

SELECT
    ARRAY_AGG(c1 ORDER BY id DESC) FILTER (WHERE c1 != ' ') c1
  , ARRAY_AGG(c2 ORDER BY id DESC) FILTER (WHERE c2 != ' ') c2
  , ARRAY_AGG(c3 ORDER BY id DESC) FILTER (WHERE c3 != ' ') c3
  , ARRAY_AGG(c4 ORDER BY id DESC) FILTER (WHERE c4 != ' ') c4
  , ARRAY_AGG(c5 ORDER BY id DESC) FILTER (WHERE c5 != ' ') c5
  , ARRAY_AGG(c6 ORDER BY id DESC) FILTER (WHERE c6 != ' ') c6
  , ARRAY_AGG(c7 ORDER BY id DESC) FILTER (WHERE c7 != ' ') c7
  , ARRAY_AGG(c8 ORDER BY id DESC) FILTER (WHERE c8 != ' ') c8
  , ARRAY_AGG(c9 ORDER BY id DESC) FILTER (WHERE c9 != ' ') c9
FROM cols
;

DROP TABLE IF EXISTS day05_steps01;

CREATE TABLE day05_steps01 AS
SELECT
    (ROW_NUMBER () OVER (ORDER BY id, s))::int id
  , (arr[4])::int from_
  , (arr[6])::int to_
FROM day05_data
JOIN LATERAL regexp_split_to_array(data, '\s+') arr ON TRUE
JOIN LATERAL GENERATE_SERIES(1, arr[2]::int) s ON TRUE
WHERE id > 10;

DROP TABLE IF EXISTS day05_steps02;

CREATE TABLE day05_steps02 AS
SELECT
    id - 10 id
  , (arr[2])::int crates
  , (arr[4])::int from_
  , (arr[6])::int to_
FROM day05_data
JOIN LATERAL regexp_split_to_array(data, '\s+') arr ON TRUE
WHERE id > 10;
