DROP TABLE IF EXISTS day01_calorie_counting;

CREATE TABLE day01_calorie_counting (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , calories INT
);

COPY day01_calorie_counting (calories)
FROM '/aoc2022_data/day01.txt'
WITH (NULL '');
