DROP TABLE IF EXISTS day07_filesystem;
CREATE TABLE day07_filesystem (
    id int primary key generated by default as identity
  , shell_output TEXT
);
COPY day07_filesystem (shell_output) FROM '/aoc2022_data/day07.txt';
