DROP TABLE IF EXISTS day02_rock_paper_scissors;
CREATE TABLE day02_rock_paper_scissors (
    id INT GENERATED BY DEFAULT AS IDENTITY
  , opponent_move char(1)
  , my_move char(1)
);
COPY day02_rock_paper_scissors (opponent_move, my_move)
FROM '/aoc2022_data/day02.txt'
WITH (FORMAT TEXT, DELIMITER ' ');

DROP TABLE IF EXISTS day02_scoring_rule;
CREATE TABLE day02_scoring_rule (
  opponent_move char(1)
, my_move char(1)
, opponent_score INT
, my_score int
);
INSERT INTO day02_scoring_rule VALUES
  ('A', 'X', 4, 4) -- draw
, ('A', 'Y', 1, 8) -- i win
, ('A', 'Z', 7, 3) -- opponent win
, ('B', 'X', 8, 1) -- opponent win
, ('B', 'Y', 5, 5) -- draw
, ('B', 'Z', 2, 9) -- i win
, ('C', 'X', 3, 7) -- i win
, ('C', 'Y', 9, 2) -- opponent wins
, ('C', 'Z', 6, 6) -- draw
;
