DROP TABLE IF EXISTS day03_rucksack_contents;

CREATE TABLE day03_rucksack_contents (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , contents TEXT
);

COPY day03_rucksack_contents (contents) FROM '/aoc2022_data/day03.txt';
