DROP TABLE IF EXISTS day04_assignments;

CREATE TABLE day04_assignments (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
  , section1 text
  , section2 text
);
COPY day04_assignments (section1, section2)
FROM '/aoc2022_data/day04.txt'
WITH (DELIMITER ',')
